from timing_trace import Trace, TRACE_VERSION
import time
print(f"TRACE_VERSION={TRACE_VERSION}")
t = Trace(prompt_id="test")
t.mark("t0_client_press")
t.mark("t1_local_recv")
t.mark("t2_local_dispatch")
t.mark("t3_modal_entry")
t.mark("t3d_prompt_start")
t.mark("t3e_execution_start")
t.mark("t6_sampler_start")
t.mark("t6_sampler_end")
t.mark("t7b_collect_start")
t.mark("t8b_outputs_collected")
t.mark("t9_modal_return")
s = t.summary()
print(f"version={s.get('trace_version')}")
print(f"derived={list(s.get('derived_ms', {}).keys())}")
print(f"quality={s.get('timing_quality')}")
print(f"quality_reason={s.get('timing_quality_reason')}")
print(f"missing={s.get('missing_timing_fields')}")
print(f"exec_ms={s.get('derived_ms', {}).get('total_input_execution_ms')}")
print("summary OK")
